name: Update Regexes

on:
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch:

jobs:
  update-regexes:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package in editable mode
        run: |
          pip install -e .

      - name: Run regex updater
        run: |
          ua_extract update_regexes

      - name: Check for changes
        id: diff_check
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: No changes, nothing to push
        if: steps.diff_check.outputs.changed == 'false'
        run: |
          echo "No regex updates. Exiting."

      - name: Commit changes
        if: steps.diff_check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update regexes"

      - name: Push changes
        if: steps.diff_check.outputs.changed == 'true'
        run: |
          git push